# Generated by Django 4.0.6 on 2022-07-25 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_list',
            fields=[
                ('Test_ID', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('Test_Suite_Name', models.CharField(default=None, max_length=120)),
                ('Test_Name', models.CharField(default=None, max_length=120)),
                ('Test_Path', models.CharField(default=None, max_length=1200)),
            ],
            options={
                'unique_together': {('Test_Suite_Name', 'Test_Path')},
            },
        ),
        migrations.CreateModel(
            name='test_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Case_ID', models.IntegerField(default=0, unique=True, verbose_name='Test_Case_ID')),
                ('Order_Of_Test', models.IntegerField(default=0, verbose_name='Order_Of_Test')),
                ('Test_Case_Description', models.CharField(default=None, max_length=1000, verbose_name='Test_Case_Description')),
                ('Test_ID', models.ForeignKey(default=0, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='tutorials.test_list', unique=True, verbose_name='Test_ID')),
            ],
            options={
                'unique_together': {('Test_ID', 'Test_Case_ID')},
            },
        ),
        migrations.CreateModel(
            name='known_error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Known_Error_ID', models.IntegerField(default=0)),
                ('Test_Result', models.CharField(default=None, max_length=120)),
                ('Test_Result_Description', models.CharField(default=None, max_length=1200)),
                ('End_Date', models.DateTimeField(blank=True)),
                ('Start_Dtae', models.DateTimeField()),
                ('Test_Case_ID', models.ForeignKey(default=0, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='tutorials.test_case', unique=True)),
            ],
        ),
    ]
