# Generated by Django 4.0.6 on 2022-07-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_remove_known_error_test_case_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='known_error',
            name='id',
        ),
        migrations.RemoveField(
            model_name='test_case',
            name='id',
        ),
        migrations.AlterField(
            model_name='known_error',
            name='Known_Error_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test_case',
            name='Test_Case_ID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='test_list',
            name='Test_ID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
