# Generated by Django 4.0.6 on 2022-07-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_remove_known_error_id_remove_test_case_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_case',
            name='Test_ID',
            field=models.ForeignKey(blank=True, default=0, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.test_list'),
        ),
        migrations.AlterField(
            model_name='test_list',
            name='Test_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
