# Generated by Django 4.0.6 on 2022-07-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_test_case_test_id_alter_test_list_test_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='known_error',
            name='Start_Dtae',
        ),
        migrations.AddField(
            model_name='known_error',
            name='Start_Date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='known_error',
            name='End_Date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
